#!/bin/bash
if [ -z "$1" ]
then
        echo "Extracts IPs from a file and prints them with their country code. Usage: ./ipwhere input_file"
else
        ip_array=( $(grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' "$1") )
        for i in "${ip_array[@]}"
        do
           country_code=$( curl -s ipinfo.io/$i | cut -d\" -f4 | grep -x '.\{2\}' )
           echo $i $country_code
        done
fi
